services:
  - type: web
    name: aurum-asd
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
